const mongoose = require('mongoose');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '.env') });
const User = require('../models/User');

const dummyUsers = [
  // ==========================================
  // ARCHITECTS (5 PROFILES)
  // ==========================================
  {
    fullName: 'Aarav Sharma',
    email: 'aarav@gmail.com',
    password: 'aarav123',
    phoneNumber: '+919820111001',
    phone: '+919820111001',
    whatsappNumber: '+919820111001',
    role: 'Architect',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    area: 'Bandra West',
    firmName: 'Aarav Sharma Architects',
    normalizedFirmName: 'aarav sharma architects',
    shortDesc: 'Award-winning sustainable & luxury residential architect.',
    about: 'Principal architect with over 10 years of experience crafting bespoke luxury villas, modern apartments, and sustainable eco-residences across Mumbai and Goa.',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    cover: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    specialization: ['Modern Luxury', 'Sustainable Architecture', 'Residential Villas', 'Interior Design'],
    serviceArea: ['Mumbai', 'Navi Mumbai', 'Thane', 'Goa'],
    experience: '10+ Years',
    rating: 4.9,
    reviews: 28,
    projects: 34,
    followersCount: 412,
    followingCount: 85,
    isVerified: true,
    profileCompletion: 95,
    latitude: 19.0596,
    longitude: 72.8295,
    formattedAddress: 'Bandra West, Mumbai, Maharashtra',
    portfolioImages: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=800&q=80'
    ],
    portfolioHighlights: [
      {
        title: 'The Glass Horizon Villa',
        projectType: 'Luxury Villa',
        location: 'Alibaug, Maharashtra',
        budget: '₹3.5 Cr',
        timeline: '14 Months',
        requirements: ['Sea Facing', 'Solar Powered', 'Infinity Pool'],
        description: 'A seamless indoor-outdoor luxury coastal villa built with sustainable materials and climate-responsive glass facades.',
        mediaUrls: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80'],
        likes: 84,
        comments: 12
      }
    ]
  },
  {
    fullName: 'Priya Mehta',
    email: 'priya@gmail.com',
    password: 'priya123',
    phoneNumber: '+919820111002',
    phone: '+919820111002',
    whatsappNumber: '+919820111002',
    role: 'Architect',
    city: 'Bengaluru',
    state: 'Karnataka',
    country: 'India',
    area: 'Indiranagar',
    firmName: 'Mehta Design Atelier',
    normalizedFirmName: 'mehta design atelier',
    shortDesc: 'Contemporary architectural design and biophilic interiors.',
    about: 'Specializing in contemporary residential architecture, minimalist spatial design, and incorporating green biophilic spaces inside urban living environments.',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
    cover: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80',
    specialization: ['Contemporary Homes', 'Biophilic Design', 'Minimalist Interiors'],
    serviceArea: ['Bengaluru', 'Mysuru', 'Hyderabad'],
    experience: '8 Years',
    rating: 4.8,
    reviews: 22,
    projects: 26,
    followersCount: 320,
    followingCount: 64,
    isVerified: true,
    profileCompletion: 92,
    latitude: 12.9784,
    longitude: 77.6408,
    formattedAddress: 'Indiranagar, Bengaluru, Karnataka',
    portfolioImages: [
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=800&q=80'
    ]
  },
  {
    fullName: 'Rohan Kapoor',
    email: 'rohan@gmail.com',
    password: 'rohan123',
    phoneNumber: '+919820111003',
    phone: '+919820111003',
    whatsappNumber: '+919820111003',
    role: 'Architect',
    city: 'Delhi',
    state: 'Delhi',
    country: 'India',
    area: 'Vasant Vihar',
    firmName: 'Kapoor Architecture Group',
    normalizedFirmName: 'kapoor architecture group',
    shortDesc: 'Commercial complexes, penthouses & master-planning.',
    about: 'Architectural planning firm focused on large-scale urban residences, corporate headquarters, and high-end residential renovations in Delhi NCR.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    cover: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
    specialization: ['Commercial High-Rise', 'Penthouse Renovations', 'Master Planning'],
    serviceArea: ['Delhi', 'Gurugram', 'Noida'],
    experience: '12 Years',
    rating: 4.9,
    reviews: 35,
    projects: 42,
    followersCount: 510,
    followingCount: 110,
    isVerified: true,
    profileCompletion: 96,
    latitude: 28.5672,
    longitude: 77.1601,
    formattedAddress: 'Vasant Vihar, New Delhi, Delhi',
    portfolioImages: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80'
    ]
  },
  {
    fullName: 'Ananya Iyer',
    email: 'ananya@gmail.com',
    password: 'ananya123',
    phoneNumber: '+919820111004',
    phone: '+919820111004',
    whatsappNumber: '+919820111004',
    role: 'Architect',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    area: 'Koregaon Park',
    firmName: 'Iyer Studio Spaces',
    normalizedFirmName: 'iyer studio spaces',
    shortDesc: 'Eco-conscious architecture and traditional-modern fusion.',
    about: 'Blending natural terracotta, stone, and passive cooling techniques with modern minimalist architectural styling for timeless living spaces.',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=600&q=80',
    cover: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    specialization: ['Eco-Conscious Homes', 'Terracotta & Stone', 'Passive Cooling Architecture'],
    serviceArea: ['Pune', 'Mumbai', 'Lonavala'],
    experience: '6 Years',
    rating: 4.7,
    reviews: 19,
    projects: 21,
    followersCount: 280,
    followingCount: 45,
    isVerified: true,
    profileCompletion: 90,
    latitude: 18.5362,
    longitude: 73.8940,
    formattedAddress: 'Koregaon Park, Pune, Maharashtra',
    portfolioImages: [
      'https://images.unsplash.com/photo-1600585152220-90363fe7e115?auto=format&fit=crop&w=800&q=80'
    ]
  },
  {
    fullName: 'Vikramaditya Rao',
    email: 'vikram@gmail.com',
    password: 'vikram123',
    phoneNumber: '+919820111005',
    phone: '+919820111005',
    whatsappNumber: '+919820111005',
    role: 'Architect',
    city: 'Hyderabad',
    state: 'Telangana',
    country: 'India',
    area: 'Jubilee Hills',
    firmName: 'V. Rao Architecture & Urbanism',
    normalizedFirmName: 'v. rao architecture & urbanism',
    shortDesc: 'Grand estate homes, corporate towers & landscape architecture.',
    about: 'With 14 years of pedigree across India and Singapore, V. Rao Architecture delivers grand residences and flagship tech-campus infrastructure.',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    cover: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80',
    specialization: ['Grand Estates', 'Tech Campuses', 'Hospitality & Resorts'],
    serviceArea: ['Hyderabad', 'Bengaluru', 'Visakhapatnam'],
    experience: '14 Years',
    rating: 5.0,
    reviews: 44,
    projects: 58,
    followersCount: 680,
    followingCount: 92,
    isVerified: true,
    profileCompletion: 98,
    latitude: 17.4319,
    longitude: 78.4073,
    formattedAddress: 'Jubilee Hills, Hyderabad, Telangana',
    portfolioImages: [
      'https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80'
    ]
  },

  // ==========================================
  // CONTRACTORS (5 PROFILES)
  // ==========================================
  {
    fullName: 'Rajesh Verma',
    email: 'rajesh@gmail.com',
    password: 'rajesh123',
    phoneNumber: '+919830222001',
    phone: '+919830222001',
    whatsappNumber: '+919830222001',
    role: 'Contractor',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    area: 'Andheri East',
    firmName: 'Verma Construction & Civil Works',
    normalizedFirmName: 'verma construction & civil works',
    contractorType: 'General Contractor',
    teamSize: '30-50 Workers',
    workCategory: ['Civil Works', 'RCC Construction', 'Plastering & Brickwork', 'Flooring'],
    serviceLocation: ['Mumbai', 'Thane', 'Navi Mumbai'],
    shortDesc: 'Premier civil contracting & structural construction specialists.',
    about: 'A-Class licensed civil contractor executing turnkey building construction, reinforced concrete frameworks, and premium multi-storey developments.',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=600&q=80',
    cover: 'https://images.unsplash.com/photo-1541888946425-d0fbb1861564?auto=format&fit=crop&w=1200&q=80',
    experience: '15 Years',
    rating: 4.8,
    reviews: 38,
    projects: 52,
    followersCount: 190,
    followingCount: 30,
    isVerified: true,
    profileCompletion: 94,
    latitude: 19.1136,
    longitude: 72.8697,
    formattedAddress: 'Andheri East, Mumbai, Maharashtra',
    portfolioImages: [
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=800&q=80'
    ]
  },
  {
    fullName: 'Suresh Patil',
    email: 'suresh@gmail.com',
    password: 'suresh123',
    phoneNumber: '+919830222002',
    phone: '+919830222002',
    whatsappNumber: '+919830222002',
    role: 'Contractor',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    area: 'Kothrud',
    firmName: 'Patil Buildcon Solutions',
    normalizedFirmName: 'patil buildcon solutions',
    contractorType: 'Turnkey Residential Contractor',
    teamSize: '25-40 Workers',
    workCategory: ['Residential Construction', 'Row Houses', 'Structural Waterproofing'],
    serviceLocation: ['Pune', 'Pimpri-Chinchwad', 'Talegaon'],
    shortDesc: 'Quality residential building contractor with turnkey delivery.',
    about: 'Delivering end-to-end villa construction, foundation excavation, plumbing layouts, and structural waterproofing with strict timeline commitments.',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=600&q=80',
    cover: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=80',
    experience: '11 Years',
    rating: 4.7,
    reviews: 29,
    projects: 37,
    followersCount: 145,
    followingCount: 22,
    isVerified: true,
    profileCompletion: 90,
    latitude: 18.5074,
    longitude: 73.8077,
    formattedAddress: 'Kothrud, Pune, Maharashtra',
    portfolioImages: [
      'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=800&q=80'
    ]
  },
  {
    fullName: 'Amitabh Singh',
    email: 'amit@gmail.com',
    password: 'amit123',
    phoneNumber: '+919830222003',
    phone: '+919830222003',
    whatsappNumber: '+919830222003',
    role: 'Contractor',
    city: 'Delhi',
    state: 'Delhi',
    country: 'India',
    area: 'Connaught Place',
    firmName: 'Singh Infra & Commercial Builders',
    normalizedFirmName: 'singh infra & commercial builders',
    contractorType: 'Commercial & Industrial Contractor',
    teamSize: '50-100 Workers',
    workCategory: ['Steel Fabrication', 'Industrial Flooring', 'Heavy Civil', 'Warehouse Sheds'],
    serviceLocation: ['Delhi NCR', 'Gurugram', 'Manesar', 'Faridabad'],
    shortDesc: 'Heavy structural steel framing & industrial plant contractor.',
    about: 'Specialized industrial contractor providing heavy steel shed fabrication, laser screed flooring, and turnkey manufacturing warehouse infrastructure.',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=600&q=80',
    cover: 'https://images.unsplash.com/photo-1541888946425-d0fbb1861564?auto=format&fit=crop&w=1200&q=80',
    experience: '18 Years',
    rating: 4.9,
    reviews: 46,
    projects: 64,
    followersCount: 310,
    followingCount: 40,
    isVerified: true,
    profileCompletion: 96,
    latitude: 28.6315,
    longitude: 77.2167,
    formattedAddress: 'Connaught Place, New Delhi, Delhi',
    portfolioImages: [
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80'
    ]
  },
  {
    fullName: 'Dinesh Choudhary',
    email: 'dinesh@gmail.com',
    password: 'dinesh123',
    phoneNumber: '+919830222004',
    phone: '+919830222004',
    whatsappNumber: '+919830222004',
    role: 'Contractor',
    city: 'Ahmedabad',
    state: 'Gujarat',
    country: 'India',
    area: 'SG Highway',
    firmName: 'Choudhary Interior & Fitout Works',
    normalizedFirmName: 'choudhary interior & fitout works',
    contractorType: 'Interior & Finishing Contractor',
    teamSize: '20-35 Workers',
    workCategory: ['False Ceiling', 'Italian Marble Fitting', 'Wall Cladding', 'Painting'],
    serviceLocation: ['Ahmedabad', 'Gandhinagar', 'Vadodara'],
    shortDesc: 'Luxury finishing, Italian marble laying, and premium fitouts.',
    about: 'Precision interior finishing contractor recognized for seamless marble bookmatching, acoustic false ceilings, and high-gloss PU paint finishes.',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=600&q=80',
    cover: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80',
    experience: '9 Years',
    rating: 4.6,
    reviews: 21,
    projects: 30,
    followersCount: 160,
    followingCount: 18,
    isVerified: true,
    profileCompletion: 89,
    latitude: 23.0338,
    longitude: 72.5850,
    formattedAddress: 'SG Highway, Ahmedabad, Gujarat',
    portfolioImages: [
      'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80'
    ]
  },
  {
    fullName: 'Manoj Nair',
    email: 'manoj@gmail.com',
    password: 'manoj123',
    phoneNumber: '+919830222005',
    phone: '+919830222005',
    whatsappNumber: '+919830222005',
    role: 'Contractor',
    city: 'Bengaluru',
    state: 'Karnataka',
    country: 'India',
    area: 'Whitefield',
    firmName: 'Nair Urban Construction',
    normalizedFirmName: 'nair urban construction',
    contractorType: 'General Building Contractor',
    teamSize: '30-50 Workers',
    workCategory: ['Civil Framework', 'Electrical Substation', 'Exterior Cladding', 'Waterproofing'],
    serviceLocation: ['Bengaluru', 'Electronic City', 'Whitefield'],
    shortDesc: 'Modern tech-park and residential apartment construction.',
    about: 'Over 13 years of expertise in fast-track modular and RCC construction for gated communities and modern apartment buildings in Bengaluru.',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
    cover: 'https://images.unsplash.com/photo-1541888946425-d0fbb1861564?auto=format&fit=crop&w=1200&q=80',
    experience: '13 Years',
    rating: 4.8,
    reviews: 34,
    projects: 48,
    followersCount: 220,
    followingCount: 35,
    isVerified: true,
    profileCompletion: 93,
    latitude: 12.9698,
    longitude: 77.7500,
    formattedAddress: 'Whitefield, Bengaluru, Karnataka',
    portfolioImages: [
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80'
    ]
  },

  // ==========================================
  // LABOUR / SKILLED WORKERS (5 PROFILES)
  // ==========================================
  {
    fullName: 'Ramesh Yadav',
    email: 'ramesh@gmail.com',
    password: 'ramesh123',
    phoneNumber: '+919840333001',
    phone: '+919840333001',
    whatsappNumber: '+919840333001',
    role: 'Labour',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    area: 'Andheri West',
    skillType: 'Mason',
    availability: 'Available',
    isAvailableForBooking: true,
    workArea: 'Andheri West, Mumbai',
    workAreaRadius: 15,
    serviceRadiusKm: 15,
    shortDesc: 'Master mason expert in brick masonry, plastering, and RCC casting.',
    about: 'Experienced mason with 7+ years of expertise in red brick, fly ash block laying, smooth internal wall plastering, and concrete slabs.',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
    cover: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=1200&q=80',
    experience: '7 Years',
    rating: 4.9,
    reviews: 24,
    projects: 68,
    followersCount: 88,
    followingCount: 12,
    isVerified: true,
    profileCompletion: 92,
    latitude: 19.1136,
    longitude: 72.8297,
    formattedAddress: 'Andheri West, Mumbai, Maharashtra'
  },
  {
    fullName: 'Santosh Kumar',
    email: 'santosh@gmail.com',
    password: 'santosh123',
    phoneNumber: '+919840333002',
    phone: '+919840333002',
    whatsappNumber: '+919840333002',
    role: 'Labour',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    area: 'Dadar',
    skillType: 'Electrician',
    availability: 'Available',
    isAvailableForBooking: true,
    workArea: 'Dadar, Mumbai',
    workAreaRadius: 20,
    serviceRadiusKm: 20,
    shortDesc: 'Certified electrician for concealed conduit wiring and DB panels.',
    about: 'Licensed wireman skilled in 3-phase commercial DB panel wiring, concealed residential conduits, smart home switchboards, and fault troubleshooting.',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    cover: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=1200&q=80',
    experience: '5 Years',
    rating: 4.8,
    reviews: 29,
    projects: 74,
    followersCount: 110,
    followingCount: 15,
    isVerified: true,
    profileCompletion: 90,
    latitude: 19.0178,
    longitude: 72.8478,
    formattedAddress: 'Dadar, Mumbai, Maharashtra'
  },
  {
    fullName: 'Mohan Lal',
    email: 'mohan@gmail.com',
    password: 'mohan123',
    phoneNumber: '+919840333003',
    phone: '+919840333003',
    whatsappNumber: '+919840333003',
    role: 'Labour',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    area: 'Bandra West',
    skillType: 'Plumber',
    availability: 'Available',
    isAvailableForBooking: true,
    workArea: 'Bandra, Mumbai',
    workAreaRadius: 15,
    serviceRadiusKm: 15,
    shortDesc: 'Expert plumber for CPVC/UPVC sanitary lines and drainage systems.',
    about: 'Specialist in high-pressure bathroom concealed plumbing, sanitaryware installation, overhead water tanks, and sewage line leak detection.',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=600&q=80',
    cover: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&w=1200&q=80',
    experience: '8 Years',
    rating: 4.9,
    reviews: 31,
    projects: 85,
    followersCount: 95,
    followingCount: 10,
    isVerified: true,
    profileCompletion: 94,
    latitude: 19.0596,
    longitude: 72.8295,
    formattedAddress: 'Bandra West, Mumbai, Maharashtra'
  },
  {
    fullName: 'Deepak Chauhan',
    email: 'deepak@gmail.com',
    password: 'deepak123',
    phoneNumber: '+919840333004',
    phone: '+919840333004',
    whatsappNumber: '+919840333004',
    role: 'Labour',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    area: 'Borivali West',
    skillType: 'Painter',
    availability: 'Available',
    isAvailableForBooking: true,
    workArea: 'Borivali, Mumbai',
    workAreaRadius: 15,
    serviceRadiusKm: 15,
    shortDesc: 'Professional painter specialized in luxury textures and exterior coating.',
    about: 'Expertise in Asian Paints Royale luxury emulsion, velvet texture walls, water-repellent exterior primers, and wood polish / PU coatings.',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=600&q=80',
    cover: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=1200&q=80',
    experience: '6 Years',
    rating: 4.7,
    reviews: 20,
    projects: 56,
    followersCount: 75,
    followingCount: 8,
    isVerified: true,
    profileCompletion: 88,
    latitude: 19.2307,
    longitude: 72.8567,
    formattedAddress: 'Borivali West, Mumbai, Maharashtra'
  },
  {
    fullName: 'Sunil Vishwakarma',
    email: 'sunil@gmail.com',
    password: 'sunil123',
    phoneNumber: '+919840333005',
    phone: '+919840333005',
    whatsappNumber: '+919840333005',
    role: 'Labour',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    area: 'Thane West',
    skillType: 'Carpenter',
    availability: 'Available',
    isAvailableForBooking: true,
    workArea: 'Thane West, Mumbai',
    workAreaRadius: 20,
    serviceRadiusKm: 20,
    shortDesc: 'Master carpenter for modular kitchen, wardrobes, and wooden door frames.',
    about: 'Expert craftsman with 10 years experience crafting marine-ply modular kitchens, sliding wardrobes, soft-close hardware fitting, and solid teak doors.',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=600&q=80',
    cover: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80',
    experience: '10 Years',
    rating: 5.0,
    reviews: 42,
    projects: 110,
    followersCount: 140,
    followingCount: 16,
    isVerified: true,
    profileCompletion: 95,
    latitude: 19.2183,
    longitude: 72.9781,
    formattedAddress: 'Thane West, Mumbai, Maharashtra'
  }
];

async function seedUsers() {
  const uri = process.env.MONGODB_URI;
  if (!uri) {
    console.error('MONGODB_URI not found in .env');
    process.exit(1);
  }

  console.log('Connecting to MongoDB Atlas...');
  await mongoose.connect(uri);
  console.log('Connected successfully!');

  console.log(`Starting to insert / update ${dummyUsers.length} dummy users...`);
  
  const createdUsers = [];

  for (const u of dummyUsers) {
    const existing = await User.findOne({ email: u.email });
    let saved;
    if (existing) {
      Object.assign(existing, u);
      saved = await existing.save();
      console.log(`[Updated] ${u.role} - ${u.fullName} (${u.email})`);
    } else {
      saved = await User.create(u);
      console.log(`[Created] ${u.role} - ${u.fullName} (${u.email})`);
    }
    createdUsers.push({
      Role: saved.role,
      Name: saved.fullName,
      Email: saved.email,
      Password: saved.password,
      City: saved.city
    });
  }

  console.log('\n================ SUMMARY OF DUMMY USERS ================');
  console.table(createdUsers);
  console.log('========================================================\n');

  await mongoose.disconnect();
  console.log('Database disconnected. All 15 dummy profiles ready!');
}

seedUsers().catch(err => {
  console.error('Error seeding users:', err);
  process.exit(1);
});
